pub static TOP_CRATES: [&str; 1000] = [
    "serde",                       // 4268
    "serde_derive",                // 3230
    "serde_json",                  // 3079
    "log",                         // 2713
    "libc",                        // 2419
    "rand",                        // 2335
    "clap",                        // 2004
    "lazy_static",                 // 1911
    "failure",                     // 1483
    "futures",                     // 1446
    "regex",                       // 1443
    "byteorder",                   // 1260
    "hyper",                       // 1233
    "chrono",                      // 1231
    "env_logger",                  // 1095
    "url",                         // 942
    "winapi",                      // 882
    "quote",                       // 812
    "syn",                         // 811
    "time",                        // 764
    "reqwest",                     // 711
    "error-chain",                 // 661
    "rustc-serialize",             // 648
    "toml",                        // 637
    "bitflags",                    // 600
    "hyper-rustls",                // 582
    "mime",                        // 534
    "proc-macro2",                 // 518
    "itertools",                   // 515
    "num-traits",                  // 512
    "tokio",                       // 492
    "bytes",                       // 472
    "tempdir",                     // 469
    "base64",                      // 463
    "structopt",                   // 460
    "num",                         // 446
    "uuid",                        // 423
    "nom",                         // 403
    "quickcheck",                  // 396
    "yup-oauth2",                  // 388
    "tokio-core",                  // 385
    "tempfile",                    // 360
    "clippy",                      // 349
    "bindgen",                     // 342
    "image",                       // 334
    "pkg-config",                  // 320
    "rayon",                       // 314
    "cc",                          // 307
    "criterion",                   // 305
    "walkdir",                     // 299
    "nix",                         // 297
    "bincode",                     // 291
    "tokio-io",                    // 285
    "num_cpus",                    // 281
    "failure_derive",              // 277
    "docopt",                      // 266
    "hex",                         // 265
    "glob",                        // 251
    "openssl",                     // 249
    "sha2",                        // 243
    "getopts",                     // 235
    "flate2",                      // 233
    "rust-crypto",                 // 227
    "parking_lot",                 // 217
    "quick-error",                 // 215
    "mio",                         // 208
    "fnv",                         // 208
    "ansi_term",                   // 208
    "serde_yaml",                  // 207
    "http",                        // 207
    "gcc",                         // 205
    "cortex-m",                    // 205
    "strsim",                      // 204
    "embedded-hal",                // 199
    "colored",                     // 199
    "dirs",                        // 196
    "yup-hyper-mock",              // 191
    "slog",                        // 181
    "rusoto_core",                 // 176
    "smallvec",                    // 171
    "ring",                        // 168
    "cfg-if",                      // 162
    "git2",                        // 161
    "csv",                         // 161
    "cortex-m-rt",                 // 158
    "semver",                      // 157
    "native-tls",                  // 150
    "rusoto_mock",                 // 145
    "pretty_assertions",           // 145
    "hyper-tls",                   // 141
    "iron",                        // 136
    "digest",                      // 136
    "term",                        // 130
    "ndarray",                     // 129
    "nalgebra",                    // 128
    "protobuf",                    // 125
    "memmap",                      // 125
    "xml-rs",                      // 123
    "crossbeam",                   // 123
    "maplit",                      // 122
    "kernel32-sys",                // 121
    "void",                        // 120
    "bare-metal",                  // 119
    "pretty_env_logger",           // 117
    "tokio-timer",                 // 116
    "curl",                        // 112
    "arrayvec",                    // 112
    "approx",                      // 112
    "vcell",                       // 111
    "cmake",                       // 108
    "proc-macro-hack",             // 107
    "either",                      // 106
    "atty",                        // 106
    "skeptic",                     // 105
    "crossbeam-channel",           // 104
    "dotenv",                      // 103
    "nb",                          // 102
    "glib-sys",                    // 101
    "proptest",                    // 100
    "matches",                     // 99
    "futures-cpupool",             // 99
    "tar",                         // 98
    "termion",                     // 97
    "generic-array",               // 97
    "indexmap",                    // 96
    "wasm-bindgen",                // 95
    "version-sync",                // 95
    "slog-term",                   // 95
    "rustc_version",               // 95
    "cgmath",                      // 95
    "yaml-rust",                   // 94
    "tokio-codec",                 // 93
    "rocket",                      // 93
    "pest",                        // 93
    "hashbrown",                   // 92
    "diesel",                      // 91
    "num-bigint",                  // 90
    "glium",                       // 90
    "actix-web",                   // 89
    "bencher",                     // 88
    "zip",                         // 87
    "serde_urlencoded",            // 86
    "percent-encoding",            // 85
    "handlebars",                  // 85
    "slab",                        // 84
    "memchr",                      // 84
    "gobject-sys",                 // 84
    "petgraph",                    // 82
    "glutin",                      // 82
    "pest_derive",                 // 81
    "serde_test",                  // 80
    "unicode-segmentation",        // 79
    "serde_codegen",               // 79
    "serde_macros",                // 77
    "rusqlite",                    // 76
    "hmac",                        // 76
    "data-encoding",               // 76
    "compiletest_rs",              // 75
    "typenum",                     // 74
    "glib",                        // 74
    "mime_guess",                  // 72
    "fern",                        // 72
    "backtrace",                   // 72
    "notify",                      // 71
    "unicode-width",               // 70
    "sdl2",                        // 70
    "r2d2",                        // 70
    "prettytable-rs",              // 70
    "phf",                         // 70
    "json",                        // 70
    "errno",                       // 70
    "encoding",                    // 70
    "threadpool",                  // 69
    "cast",                        // 69
    "rustyline",                   // 68
    "net2",                        // 68
    "argparse",                    // 68
    "postgres",                    // 67
    "linked-hash-map",             // 67
    "serde_bytes",                 // 66
    "structopt-derive",            // 65
    "pulldown-cmark",              // 65
    "hyper-native-tls",            // 65
    "derive_more",                 // 65
    "gtk",                         // 64
    "enum_primitive",              // 64
    "untrusted",                   // 63
    "syntex",                      // 63
    "indicatif",                   // 63
    "bit-vec",                     // 63
    "rpassword",                   // 62
    "libloading",                  // 62
    "heck",                        // 62
    "gl",                          // 62
    "slog-async",                  // 61
    "sha3",                        // 61
    "libimagerror",                // 61
    "ctrlc",                       // 61
    "winit",                       // 60
    "gfx",                         // 60
    "futures-preview",             // 60
    "tokio-tls",                   // 59
    "ordered-float",               // 59
    "crc",                         // 59
    "tiny-keccak",                 // 58
    "redis",                       // 58
    "num-complex",                 // 58
    "md5",                         // 58
    "assert_matches",              // 58
    "termcolor",                   // 57
    "sha1",                        // 57
    "trackable",                   // 56
    "derive_builder",              // 56
    "blake2",                      // 56
    "actix",                       // 56
    "simplelog",                   // 55
    "num-integer",                 // 55
    "httparse",                    // 55
    "stdweb",                      // 54
    "sodiumoxide",                 // 54
    "sha-1",                       // 54
    "tokio-tcp",                   // 53
    "tokio-service",               // 53
    "rmp-serde",                   // 53
    "libimagstore",                // 53
    "config",                      // 52
    "cookie",                      // 51
    "console",                     // 51
    "tokio-proto",                 // 50
    "router",                      // 50
    "pbr",                         // 50
    "objc",                        // 50
    "quick-xml",                   // 49
    "cargo",                       // 49
    "rusttype",                    // 48
    "rand_core",                   // 48
    "rustls",                      // 47
    "lalrpop-util",                // 47
    "directories",                 // 47
    "unicase",                     // 46
    "simple_logger",               // 46
    "ignore",                      // 46
    "difference",                  // 46
    "syntex_syntax",               // 45
    "fs2",                         // 45
    "arrayref",                    // 45
    "web-sys",                     // 44
    "url_serde",                   // 44
    "serde_cbor",                  // 44
    "libflate",                    // 44
    "assert_cmd",                  // 44
    "xdg",                         // 43
    "tera",                        // 43
    "open",                        // 43
    "hex-literal",                 // 43
    "toml-query",                  // 42
    "rocket_contrib",              // 42
    "piston_window",               // 42
    "i2cdev",                      // 42
    "humantime",                   // 42
    "x11",                         // 41
    "try_from",                    // 41
    "tokio-executor",              // 41
    "spin",                        // 41
    "secp256k1",                   // 41
    "linux-embedded-hal",          // 41
    "vec_map",                     // 40
    "phf_codegen",                 // 40
    "lalrpop",                     // 40
    "filetime",                    // 40
    "cargo_metadata",              // 40
    "bit-set",                     // 40
    "websocket",                   // 39
    "webpki",                      // 39
    "tokio-reactor",               // 39
    "shell-words",                 // 39
    "log4rs",                      // 39
    "hostname",                    // 39
    "bufstream",                   // 39
    "assert_cli",                  // 39
    "ron",                         // 38
    "derivative",                  // 38
    "combine",                     // 38
    "users",                       // 37
    "unwrap",                      // 37
    "unicode-normalization",       // 37
    "png",                         // 37
    "libimagrt",                   // 37
    "gio-sys",                     // 37
    "cortex-m-semihosting",        // 37
    "js-sys",                      // 36
    "crossbeam-utils",             // 36
    "tokio-uds",                   // 35
    "subtle",                      // 35
    "spectral",                    // 35
    "rand_xorshift",               // 35
    "panic-halt",                  // 35
    "mockito",                     // 35
    "libimagutil",                 // 35
    "jsonrpc-core",                // 35
    "app_dirs",                    // 35
    "ws",                          // 34
    "tabwriter",                   // 34
    "panic-semihosting",           // 34
    "encoding_rs",                 // 34
    "diff",                        // 34
    "core-foundation",             // 34
    "alga",                        // 34
    "winreg",                      // 33
    "typemap",                     // 33
    "serde-xml-rs",                // 33
    "scoped_threadpool",           // 33
    "piston2d-graphics",           // 33
    "html5ever",                   // 33
    "winapi-build",                // 32
    "version_check",               // 32
    "user32-sys",                  // 32
    "tokio-threadpool",            // 32
    "rust-ini",                    // 32
    "num-derive",                  // 32
    "gstreamer-sys",               // 32
    "gfx_device_gl",               // 32
    "cairo-rs",                    // 32
    "blake2-rfc",                  // 32
    "vecmath",                     // 31
    "unicode-xid",                 // 31
    "syntect",                     // 31
    "synstructure",                // 31
    "specs",                       // 31
    "quickcheck_macros",           // 31
    "piston",                      // 31
    "peg",                         // 31
    "openssl-probe",               // 31
    "gl_generator",                // 31
    "gdk",                         // 31
    "euclid",                      // 31
    "dbus",                        // 31
    "regex-syntax",                // 30
    "multipart",                   // 30
    "itoa",                        // 30
    "gio",                         // 30
    "etcommon-bigint",             // 30
    "derive-new",                  // 30
    "cocoa",                       // 30
    "block-cipher-trait",          // 30
    "Inflector",                   // 30
    "unix_socket",                 // 29
    "typed-arena",                 // 29
    "term_size",                   // 29
    "stable_deref_trait",          // 29
    "siphasher",                   // 29
    "select",                      // 29
    "fibers",                      // 29
    "curve25519-dalek",            // 29
    "chan",                        // 29
    "bzip2",                       // 29
    "wasm-bindgen-test",           // 28
    "termios",                     // 28
    "rocket_codegen",              // 28
    "lru-cache",                   // 28
    "heapsize",                    // 28
    "gtk-sys",                     // 28
    "fs_extra",                    // 28
    "ed25519-dalek",               // 28
    "widestring",                  // 27
    "stderrlog",                   // 27
    "solana-sdk",                  // 27
    "rmp",                         // 27
    "predicates",                  // 27
    "parity-wasm",                 // 27
    "mount",                       // 27
    "float-cmp",                   // 27
    "erased-serde",                // 27
    "which",                       // 26
    "webpki-roots",                // 26
    "strum_macros",                // 26
    "reproto-core",                // 26
    "pistoncore-input",            // 26
    "human-panic",                 // 26
    "bytecodec",                   // 26
    "xz2",                         // 25
    "twox-hash",                   // 25
    "strum",                       // 25
    "scraper",                     // 25
    "rustc-demangle",              // 25
    "quicli",                      // 25
    "openssl-sys",                 // 25
    "likely",                      // 25
    "globset",                     // 25
    "gfx_window_glutin",           // 25
    "fxhash",                      // 25
    "futures-core",                // 25
    "find_folder",                 // 25
    "embedded-hal-mock",           // 25
    "cursive",                     // 25
    "clear_on_drop",               // 25
    "assert_approx_eq",            // 25
    "tokio-rustls",                // 24
    "tiny_http",                   // 24
    "shlex",                       // 24
    "rustc-hex",                   // 24
    "owning_ref",                  // 24
    "md-5",                        // 24
    "gfx_core",                    // 24
    "derive-error",                // 24
    "unreachable",                 // 23
    "tokio-process",               // 23
    "slog-stdlog",                 // 23
    "rgb",                         // 23
    "opaque-debug",                // 23
    "mysql",                       // 23
    "maidsafe_utilities",          // 23
    "isatty",                      // 23
    "gfx-hal",                     // 23
    "futures-core-preview",        // 23
    "fallible-iterator",           // 23
    "dialoguer",                   // 23
    "conv",                        // 23
    "chrono-tz",                   // 23
    "capnp",                       // 23
    "bitcoin",                     // 23
    "slog-scope",                  // 22
    "seahash",                     // 22
    "scopeguard",                  // 22
    "protoc-rust",                 // 22
    "pnet",                        // 22
    "palette",                     // 22
    "mio-extras",                  // 22
    "hound",                       // 22
    "goblin",                      // 22
    "geo",                         // 22
    "ethereum-types",              // 22
    "custom_derive",               // 22
    "assert",                      // 22
    "xcb",                         // 21
    "vergen",                      // 21
    "trust-dns-resolver",          // 21
    "tokio-current-thread",        // 21
    "signal-hook",                 // 21
    "shellexpand",                 // 21
    "serial",                      // 21
    "rustc-hash",                  // 21
    "pbkdf2",                      // 21
    "num-rational",                // 21
    "notify-rust",                 // 21
    "mktemp",                      // 21
    "foreign-types",               // 21
    "core-graphics",               // 21
    "bs58",                        // 21
    "bit_field",                   // 21
    "tokio-signal",                // 20
    "string_cache",                // 20
    "staticfile",                  // 20
    "snap",                        // 20
    "rand_chacha",                 // 20
    "pad",                         // 20
    "llvm-sys",                    // 20
    "hyper-openssl",               // 20
    "gstreamer",                   // 20
    "clipboard",                   // 20
    "chan-signal",                 // 20
    "bson",                        // 20
    "block-buffer",                // 20
    "zeroize",                     // 19
    "yansi",                       // 19
    "urlencoded",                  // 19
    "shader_version",              // 19
    "serde_qs",                    // 19
    "libusb",                      // 19
    "lazycell",                    // 19
    "juniper",                     // 19
    "indoc",                       // 19
    "idna",                        // 19
    "geo-types",                   // 19
    "expectest",                   // 19
    "exitfailure",                 // 19
    "cairo-sys-rs",                // 19
    "zmq",                         // 18
    "x11-dl",                      // 18
    "unic-ucd-version",            // 18
    "unic-char-range",             // 18
    "tungstenite",                 // 18
    "term-painter",                // 18
    "subprocess",                  // 18
    "static_assertions",           // 18
    "simd",                        // 18
    "ripemd160",                   // 18
    "plugin",                      // 18
    "pancurses",                   // 18
    "newtype_derive",              // 18
    "ndarray-rand",                // 18
    "mint",                        // 18
    "libz-sys",                    // 18
    "imgui",                       // 18
    "hibitset",                    // 18
    "glfw",                        // 18
    "gdi32-sys",                   // 18
    "enum-primitive-derive",       // 18
    "crypto-mac",                  // 18
    "core-foundation-sys",         // 18
    "console_error_panic_hook",    // 18
    "bigdecimal",                  // 18
    "base58",                      // 18
    "wayland-client",              // 17
    "unindent",                    // 17
    "tokio-fs",                    // 17
    "textwrap",                    // 17
    "text_io",                     // 17
    "terminal_size",               // 17
    "shred",                       // 17
    "rustdoc-stripper",            // 17
    "redox_syscall",               // 17
    "prometheus",                  // 17
    "pistoncore-sdl2_window",      // 17
    "objc-foundation",             // 17
    "mach",                        // 17
    "lz4",                         // 17
    "libp2p-core",                 // 17
    "jemallocator",                // 17
    "gif",                         // 17
    "geojson",                     // 17
    "gdk-sys",                     // 17
    "gdk-pixbuf-sys",              // 17
    "gdk-pixbuf",                  // 17
    "dpdk-sys",                    // 17
    "crunchy",                     // 17
    "bytecount",                   // 17
    "base32",                      // 17
    "abscissa",                    // 17
    "xmltree",                     // 16
    "wabt",                        // 16
    "vulkano",                     // 16
    "unic-char-property",          // 16
    "tls-api",                     // 16
    "thread_profiler",             // 16
    "target-lexicon",              // 16
    "sys-info",                    // 16
    "svg",                         // 16
    "solana-logger",               // 16
    "socket2",                     // 16
    "serialport",                  // 16
    "rustfft",                     // 16
    "rust_sodium",                 // 16
    "rodio",                       // 16
    "rand_os",                     // 16
    "prost",                       // 16
    "languageserver-types",        // 16
    "ipnetwork",                   // 16
    "iovec",                       // 16
    "getset",                      // 16
    "flexi_logger",                // 16
    "duct",                        // 16
    "crc16",                       // 16
    "cbindgen",                    // 16
    "cargo-husky",                 // 16
    "allegro_util",                // 16
    "wasm-bindgen-futures",        // 15
    "warp",                        // 15
    "tokio-tungstenite",           // 15
    "tendril",                     // 15
    "syntex_errors",               // 15
    "stream-cipher",               // 15
    "sloggers",                    // 15
    "slog-json",                   // 15
    "simple-error",                // 15
    "sgx_types",                   // 15
    "rocksdb",                     // 15
    "pin-utils",                   // 15
    "persistent",                  // 15
    "pathdiff",                    // 15
    "packed_simd",                 // 15
    "ordermap",                    // 15
    "openblas-src",                // 15
    "nickel",                      // 15
    "multimap",                    // 15
    "metadeps",                    // 15
    "libm",                        // 15
    "lark-debug-with",             // 15
    "iron-test",                   // 15
    "insta",                       // 15
    "htmlescape",                  // 15
    "heapless",                    // 15
    "genmesh",                     // 15
    "futures-io",                  // 15
    "fixedbitset",                 // 15
    "etcommon-hexutil",            // 15
    "drone-core",                  // 15
    "downcast-rs",                 // 15
    "daemonize",                   // 15
    "bio",                         // 15
    "amethyst_core",               // 15
    "aes",                         // 15
    "webbrowser",                  // 14
    "wait-timeout",                // 14
    "vcpkg",                       // 14
    "urlencoding",                 // 14
    "trust-dns",                   // 14
    "thread-id",                   // 14
    "sgx-isa",                     // 14
    "serde_ignored",               // 14
    "serde-value",                 // 14
    "scoped-tls",                  // 14
    "rustfmt",                     // 14
    "routing",                     // 14
    "reproto-manifest",            // 14
    "quasi",                       // 14
    "piston2d-opengl_graphics",    // 14
    "phf_macros",                  // 14
    "pango",                       // 14
    "number_prefix",               // 14
    "mustache",                    // 14
    "lru_time_cache",              // 14
    "lodepng",                     // 14
    "linefeed",                    // 14
    "libsecp256k1",                // 14
    "lark-intern",                 // 14
    "inotify",                     // 14
    "humansize",                   // 14
    "hidapi",                      // 14
    "get_if_addrs",                // 14
    "fst",                         // 14
    "ethereum-hexutil",            // 14
    "diesel_migrations",           // 14
    "cty",                         // 14
    "crossbeam-epoch",             // 14
    "cpython",                     // 14
    "cpal",                        // 14
    "conduit",                     // 14
    "bodyparser",                  // 14
    "bitcoin_hashes",              // 14
    "aster",                       // 14
    "anymap",                      // 14
    "antidote",                    // 14
    "actix-service",               // 14
    "wayland-sys",                 // 13
    "trust-dns-proto",             // 13
    "thread_local",                // 13
    "syslog",                      // 13
    "strfmt",                      // 13
    "sputnikvm",                   // 13
    "slug",                        // 13
    "signatory",                   // 13
    "shell-escape",                // 13
    "shared_library",              // 13
    "scoped-pool",                 // 13
    "rustc-test",                  // 13
    "rust_decimal",                // 13
    "rss",                         // 13
    "rlua",                        // 13
    "reproto-trans",               // 13
    "r2d2_redis",                  // 13
    "procinfo",                    // 13
    "pistoncore-glutin_window",    // 13
    "once_cell",                   // 13
    "object",                      // 13
    "objc_id",                     // 13
    "num-iter",                    // 13
    "nodrop",                      // 13
    "multiaddr",                   // 13
    "mongodb",                     // 13
    "libsodium-sys",               // 13
    "libimagentrylink",            // 13
    "lark-string",                 // 13
    "kuchiki",                     // 13
    "jsonwebtoken",                // 13
    "gstreamer-base-sys",          // 13
    "gimli",                       // 13
    "gdnative_bindings_generator", // 13
    "fuse",                        // 13
    "fibers_global",               // 13
    "ethereum-rlp",                // 13
    "ethereum-bigint",             // 13
    "err-derive",                  // 13
    "embedded-graphics",           // 13
    "elastic-array",               // 13
    "dtoa",                        // 13
    "conrod",                      // 13
    "codespan",                    // 13
    "chashmap",                    // 13
    "ascii",                       // 13
    "zstd",                        // 12
    "ws2_32-sys",                  // 12
    "unsigned-varint",             // 12
    "uint",                        // 12
    "toml_edit",                   // 12
    "tokio-openssl",               // 12
    "take_mut",                    // 12
    "sysfs_gpio",                  // 12
    "stdweb-derive",               // 12
    "spidev",                      // 12
    "scroll",                      // 12
    "sample",                      // 12
    "rustbox",                     // 12
    "rug",                         // 12
    "rprompt",                     // 12
    "rlp",                         // 12
    "rental",                      // 12
    "random",                      // 12
    "pyo3",                        // 12
    "prometrics",                  // 12
    "portaudio",                   // 12
    "plist",                       // 12
    "pistoncore-window",           // 12
    "paste",                       // 12
    "ndarray-linalg",              // 12
    "ncurses",                     // 12
    "miow",                        // 12
    "minifb",                      // 12
    "macro-attr",                  // 12
    "lettre",                      // 12
    "leb128",                      // 12
    "integer-encoding",            // 12
    "i3ipc",                       // 12
    "hyperx",                      // 12
    "hashmap_core",                // 12
    "half",                        // 12
    "gdnative-common",             // 12
    "filters",                     // 12
    "etcommon-rlp",                // 12
    "dimensioned",                 // 12
    "cranelift-codegen",           // 12
    "cortex-m-rtfm",               // 12
    "built",                       // 12
    "brotli",                      // 12
    "aho-corasick",                // 12
    "actix-rt",                    // 12
    "actix-http",                  // 12
    "abstract-ns",                 // 12
    "x25519-dalek",                // 11
    "wio",                         // 11
    "tokio-udp",                   // 11
    "tokio-sync",                  // 11
    "temporary",                   // 11
    "tc_core",                     // 11
    "sxd-document",                // 11
    "susydev-jsonrpc-core",        // 11
    "statrs",                      // 11
    "shred-derive",                // 11
    "separator",                   // 11
    "rlibc",                       // 11
    "reproto-backend",             // 11
    "r2d2_postgres",               // 11
    "primal",                      // 11
    "piston-texture",              // 11
    "pem",                         // 11
    "ocl",                         // 11
    "numtoa",                      // 11
    "mio-uds",                     // 11
    "loggerv",                     // 11
    "libimagentryedit",            // 11
    "libflo_module",               // 11
    "lark-entity",                 // 11
    "keccak-hasher",               // 11
    "inflate",                     // 11
    "imgref",                      // 11
    "imageproc",                   // 11
    "if_chain",                    // 11
    "httpdate",                    // 11
    "hkdf",                        // 11
    "grin_util",                   // 11
    "genco",                       // 11
    "eui48",                       // 11
    "enum_derive",                 // 11
    "cpp_utils",                   // 11
    "cookie-factory",              // 11
    "constant_time_eq",            // 11
    "comrak",                      // 11
    "collision",                   // 11
    "cognitive-qualia",            // 11
    "clang-sys",                   // 11
    "capnpc",                      // 11
    "byte-tools",                  // 11
    "atsamd-hal",                  // 11
    "amethyst_assets",             // 11
    "allegro-sys",                 // 11
    "adler32",                     // 11
    "actix-codec",                 // 11
    "xmas-elf",                    // 10
    "wee_alloc",                   // 10
    "volatile-register",           // 10
    "unsafe-any",                  // 10
    "uname",                       // 10
    "tui",                         // 10
    "tokio-retry",                 // 10
    "tokio-async-await",           // 10
    "tk-listen",                   // 10
    "tk-http",                     // 10
    "textnonce",                   // 10
    "susy-jsonrpc-core",           // 10
    "stopwatch",                   // 10
    "slog-stream",                 // 10
    "shrev",                       // 10
    "sgxs",                        // 10
    "servo-freetype-sys",          // 10
    "sdl2-sys",                    // 10
    "ryu",                         // 10
    "rust-lzma",                   // 10
    "rust-base58",                 // 10
    "rusoto_s3",                   // 10
    "rusoto_dynamodb",             // 10
    "rulinalg",                    // 10
    "rouille",                     // 10
    "regex_macros",                // 10
    "range",                       // 10
    "qt_core",                     // 10
    "qt_build_tools",              // 10
    "qrcode",                      // 10
    "prost-build",                 // 10
    "pcap",                        // 10
    "panic-abort",                 // 10
    "pango-sys",                   // 10
    "os_type",                     // 10
    "noise",                       // 10
    "mopa",                        // 10
    "modifier",                    // 10
    "mdbook",                      // 10
    "lock_api",                    // 10
    "liquid",                      // 10
    "lark-error",                  // 10
    "lark-collections",            // 10
    "jni",                         // 10
    "is-match",                    // 10
    "interledger-service",         // 10
    "interledger-packet",          // 10
    "im",                          // 10
    "hash-db",                     // 10
    "gtk-rs-lgpl-docs",            // 10
    "gpgme",                       // 10
    "gnuplot",                     // 10
    "gleam",                       // 10
    "futures-util-preview",        // 10
    "futures-timer",               // 10
    "fixed-hash",                  // 10
    "exitcode",                    // 10
    "evm",                         // 10
    "ethabi",                      // 10
    "elf",                         // 10
    "dpdk-core",                   // 10
    "docmatic",                    // 10
    "cranelift-entity",            // 10
    "cpp",                         // 10
    "commandext",                  // 10
    "blas-src",                    // 10
    "backoff",                     // 10
    "atomic_immut",                // 10
    "atomic",                      // 10
    "RustyXML",                    // 10
    "wavefront_obj",               // 9
    "vulkano-win",                 // 9
    "vte",                         // 9
    "v_htmlescape",                // 9
    "utils",                       // 9
    "twoway",                      // 9
    "sysconf",                     // 9
    "syscall",                     // 9
    "swagger",                     // 9
    "structdoc",                   // 9
    "shell32-sys",                 // 9
    "servo-fontconfig",            // 9
    "rusticata-macros",            // 9
    "rusoto_credential",           // 9
    "route-recognizer",            // 9
    "rotor",                       // 9
    "reproto-naming",              // 9
    "remove_dir_all",              // 9
    "relative-path",               // 9
    "raw-cpuid",                   // 9
    "rand_hc",                     // 9
    "r2d2-diesel",                 // 9
    "quasi_macros",                // 9
    "prototty_render",             // 9
    "prost-derive",                // 9
    "pretty-bytes",                // 9
    "pom",                         // 9
    "page_size",                   // 9
    "orbclient",                   // 9
    "ole32-sys",                   // 9
    "odds",                        // 9
    "mkdirp",                      // 9
    "make-cmd",                    // 9
    "mac",                         // 9
    "loca",                        // 9
    "libp2p-tcp",                  // 9
    "lark-span",                   // 9
    "language-tags",               // 9
    "jsonrpc-http-server",         // 9
    "itertools-num",               // 9
    "irc",                         // 9
    "horrorshow",                  // 9
    "grin_core",                   // 9
    "gluon",                       // 9
    "ggez",                        // 9
    "futures-await",               // 9
    "flame",                       // 9
    "escargot",                    // 9
    "dot",                         // 9
    "crossterm",                   // 9
    "crossbeam-deque",             // 9
    "coord_2d",                    // 9
    "context",                     // 9
    "common_failures",             // 9
    "collect-mac",                 // 9
    "clock_ticks",                 // 9
    "cli_test_dir",                // 9
    "clang",                       // 9
    "camera_controllers",          // 9
    "bus",                         // 9
    "block",                       // 9
    "blas",                        // 9
    "bcrypt",                      // 9
    "atomicwrites",                // 9
    "arc-swap",                    // 9
    "amethyst_renderer",           // 9
    "amethyst",                    // 9
    "allegro",                     // 9
    "aes-ctr",                     // 9
    "xkbcommon",                   // 8
    "xio_base_datatypes",          // 8
    "wayland-server",              // 8
    "utf8-ranges",                 // 8
    "unidecode",                   // 8
    "treexml",                     // 8
    "tobj",                        // 8
    "timebomb",                    // 8
    "timber",                      // 8
    "slice-deque",                 // 8
    "shaderc",                     // 8
    "semver-parser",               // 8
    "self_update",                 // 8
    "security-framework",          // 8
    "secstr",                      // 8
    "safe_core",                   // 8
    "rust-extra",                  // 8
    "rppal",                       // 8
    "riker",                       // 8
    "retry",                       // 8
    "relevant",                    // 8
    "ref_slice",                   // 8
    "r0",                          // 8
    "quasi_codegen",               // 8
    "qt_gui",                      // 8
    "protoc",                      // 8
    "procedural-masquerade",       // 8
    "pretty",                      // 8
    "permutohedron",               // 8
    "params",                      // 8
    "panic_rtt",                   // 8
    "p-macro",                     // 8
    "os_pipe",                     // 8
    "obj",                         // 8
    "ns-std-threaded",             // 8
    "noisy_float",                 // 8
    "nearly_eq",                   // 8
    "ncollide_math",               // 8
    "mmap",                        // 8
    "missing_mpl",                 // 8
    "mio-named-pipes",             // 8
    "minidom",                     // 8
    "lyon_path",                   // 8
    "logger",                      // 8
    "local-encoding",              // 8
    "libimaginteraction",          // 8
    "lark-ty",                     // 8
    "lark-parser",                 // 8
    "lark-hir",                    // 8
    "lark-debug-derive",           // 8
    "kiss3d",                      // 8
    "keccak-hash",                 // 8
    "kailua_env",                  // 8
    "jni-sys",                     // 8
    "ieee754",                     // 8
    "i2csensors",                  // 8
    "httpcodec",                   // 8
    "heim-common",                 // 8
    "hamcrest",                    // 8
    "grpcio",                      // 8
    "grpc",                        // 8
    "gluon_base",                  // 8
    "gltf",                        // 8
    "globwalk",                    // 8
    "gir-format-check",            // 8
    "futures-util",                // 8
    "futures-channel-preview",     // 8
    "fps_counter",                 // 8
    "flatbuffers",                 // 8
    "fibers_rpc",                  // 8
    "deflate",                     // 8
    "darling",                     // 8
    "cstr-argument",               // 8
    "cssparser",                   // 8
    "crypto-hash",                 // 8
    "cretonne-codegen",            // 8
    "crc32fast",                   // 8
    "cpp_build",                   // 8
    "core_io",                     // 8
    "const-cstr",                  // 8
    "codespan-reporting",          // 8
    "chrono-humanize",             // 8
    "carboxyl",                    // 8
    "cannyls",                     // 8
];
